### ISSUE TITLE
Optimize property fetching

### ISSUE THREAD

**Issue by rmagen** [rmagen/unipop#31]
### Current querying behavior
- Vertex - fetch all properties + any "inner" edges and their properties.
- Edge - fetch all properties + both vertices and their properties.
  - If a vertex's schema is of type 'ref', its properties will only be fetched when it passes through a `UniGraphVertexPropertiesSideEffectStep`, a step that comes before any step that uses properties, and issues a `DeferredVertexQuery`. This ensures that the vertices will only be queried if and when its needed (i.e. lazy loading).

### Problems
1. When an Element is queried, all its properties are fetched, whether or not they are needed by this traversal.
2. When a Vertex is queried, all its "inner" edges are fetched, whether or not they are needed by this traversal.

This issue tries to solve problem 1. We should probably create another ticket for solving problem 2  in the future.

### Solution suggestion
SearchQuery/SearchVertexQuery/DeferredVertexQuery should pass a list of property keys needed from the queried element. `UniGraphPropertiesStepStrategy` should provide the property lists to the querying steps by analyzing the traversal. Scenarios:
1. No step in the traversal needs any property - empty list.
2. Step(s) in the traversal need specific property(s) - property list.
3. Step(s) in the traversal iterate over all properties - `null` list.
4. Unknown (the strategy couldn't identify which properties are needed) - `null` list. ???

Next, when a Controller receives these queries it should only fetch the relavent properties, or not issue a query at all when possible.

**Comment by rmagen** [comment]
@seanbarzilay see the failing tests following my changes to an empty set (I accidentally commited  this to master...)
Please fix the tests :)

**Comment by rmagen** [comment]
Also, why does `UniVertexStep` query `DeferredVertex` immediately after the edge query? Doesn't this defeat the point of deferring?

**Comment by seanbarzilay** [comment]
@rmagen if you know you need a certain property or all properties from a vertex than it doesn't matter when are you querying it's properties

**Comment by rmagen** [comment]
It does because other steps might filter out the vertex before its needed. But
lets leave it as it is for now.. How about those failing tests? :)

  

On Jun 27 2016, at 7:56 am, sbarzilay &lt;notifications@github.com&gt; wrote:  

>
[@rmagen](https://github.com/rmagen&r=cmVwbHkrMDA2ZDE1ZjM4NWM4Yjc5Y2FhZGM0NTlhYjc4YmMyZjdlYmZmYTk2YjYxODk4NjhlOTJjZjAwMDAwMDAxMTM4ODc0MGM5MmExNjljZTA5MzU2YzI0QHJlcGx5LmdpdGh1Yi5jb20=)
if you know you need a certain property or all properties from a vertex than
it doesn't matter when are you querying it's properties

>

> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/rmagen/unipop/issues/31#issuecomment-228654057&r=cmVwbHkrMDA2ZDE1ZjM4NWM4Yjc5Y2FhZGM0NTlhYjc4YmMyZjdlYmZmYTk2YjYxODk4NjhlOTJjZjAwMDAwMDAxMTM4ODc0MGM5MmExNjljZTA5MzU2YzI0QHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the
thread](https://github.com/notifications/unsubscribe/AG0V80CCACERJK9lXCRUHp8Pnk70n9a4ks5qP1gMgaJpZM4IdH77&r=cmVwbHkrMDA2ZDE1ZjM4NWM4Yjc5Y2FhZGM0NTlhYjc4YmMyZjdlYmZmYTk2YjYxODk4NjhlOTJjZjAwMDAwMDAxMTM4ODc0MGM5MmExNjljZTA5MzU2YzI0QHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon/AG0V8wRZ7LmNPkG9EpeVbboBjFKRKBHqks5qP1gMgaJpZM4IdH77.gif)
