### ISSUE TITLE
Dependency convergence error on build

### ISSUE THREAD

**Issue by mpollmeier** [rmagen/unipop#7]
This sounds cool, so I wanted to give unipop-elastic a try. 
Is there a jar hosted on some public repository?

When I build it manually I get the following dependency convergence error, which I couldn't even fix when adding a direct dependency from unipop-elastic on snakeyaml:1.15

```
Failed while enforcing releasability the error(s) are [
Dependency convergence error for org.yaml:snakeyaml:1.15 paths to dependency are:
+-unipop:unipop-elastic:0.1
  +-unipop:unipop-core:0.1
    +-org.apache.tinkerpop:gremlin-core:3.0.2-incubating
      +-org.yaml:snakeyaml:1.15
and
+-unipop:unipop-elastic:0.1
  +-unipop:unipop-core:0.1
    +-org.yaml:snakeyaml:1.15
and
+-unipop:unipop-elastic:0.1
  +-org.elasticsearch:elasticsearch:1.7.3
    +-org.yaml:snakeyaml:1.12
]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Unipop ............................................. SUCCESS [  0.627 s]
[INFO] Unipop :: Core ..................................... SUCCESS [  0.762 s]
[INFO] Unipop :: Elasticsearch Controllers ................ FAILURE [  0.709 s]
[INFO] Unipop :: JDBC Controllers ......................... SKIPPED
[INFO] Unipop :: Integration tests ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

**Comment by rmagen** [comment]
Huh.. I actually never used mvn to build the project (I just compile from
intelliJ).
I'll need to look into this.
Thanks!

**Comment by Blakko** [comment]
I guess this issue can be closed now :)

**Comment by jccq** [comment]
Glad to see it back :)

**Comment by rmagen** [comment]
Big updates soon :)

**Comment by jccq** [comment]
we have developed it considerably internally since last time.. but lets see
if we can sync up still and contribute back :)

On Wed, May 11, 2016 at 2:01 PM, rmagen <notifications@github.com> wrote:

> Big updates soon :)
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/rmagen/unipop/issues/7#issuecomment-218439020>
>



-- 
Giovanni Tummarello
CEO - SIREn Solutions

**Comment by rmagen** [comment]
I'm adding an issue for implementing "joins". I'm counting on your plugin for the Elasticsearch side of things. 
I really hope we can sync up :)
Are you still using Unipop? Have you divereged from the code significantly?
